apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jbuck-t4-poi-map-app-dev
  annotations:
    argocd/app-name: jbuck-t4-poi-map-app-dev
    backstage.io/kubernetes-id: jbuck-t4-poi-map-app
    backstage.io/kubernetes-namespace: jbuck-t4
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-ms/jbuck-t4-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.igb2792k.eastus2.aroapp.io/dev-pipelines/ns/jbuck-t4/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.igb2792k.eastus2.aroapp.io/k8s/ns/jbuck-t4/deployments/jbuck-t4-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.igb2792k.eastus2.aroapp.io/#https://github.com/rhdh-ms/jbuck-t4-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://jbuck-t4-poi-map-app-jbuck-t4.apps.igb2792k.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/jeremiahbuckley"
  system: workshop-system-jbuck-t4
  consumesApis:
    - gateway-api-jbuck-t4
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-jbuck-t4
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/jeremiahbuckley"
